In [1]:
import pandas as pd
import numpy as np

In [3]:
def closestNumbers(numbers):
    # Sort the numbers to make it easier to find pairs with the smallest differences
    numbers.sort()

    # Initialize the minimum difference to a large number
    min_diff = float('inf')

    # List to store pairs with the minimum difference
    pairs = []

    # Find the minimum difference
    for i in range(len(numbers) - 1):
        diff = abs(numbers[i + 1] - numbers[i])
        if diff < min_diff:
            min_diff = diff
            pairs = [(numbers[i], numbers[i + 1])]
        elif diff == min_diff:
            pairs.append((numbers[i], numbers[i + 1]))

    # Print the pairs
    for pair in pairs:
        print(pair)

# Example usage
numbers = [4,2,1,3]
closestNumbers(numbers)

(1, 2)
(2, 3)
(3, 4)


In [4]:
def closestNumbers(numbers):
    # Sort the numbers to make it easier to find pairs with the smallest differences
    numbers.sort()

    # Dictionary to store pairs with their differences
    diff_dict = {}

    # Find the differences and store pairs in the dictionary
    for i in range(len(numbers) - 1):
        diff = numbers[i + 1] - numbers[i]
        if diff not in diff_dict:
            diff_dict[diff] = [(numbers[i], numbers[i + 1])]
        else:
            diff_dict[diff].append((numbers[i], numbers[i + 1]))

    # Find the minimum difference
    min_diff = min(diff_dict.keys())

    # Return the pairs with the minimum difference
    return diff_dict[min_diff]

# Example usage
numbers = [4, 2, 1, 3]
print(closestNumbers(numbers))

[(1, 2), (2, 3), (3, 4)]


In [7]:
def max_positive_prefix_sums(arr):
    # Step 1: Sort the array in descending order
    arr.sort(reverse=True)
    
    # Step 2: Initialize variables for prefix sum and count of positive prefix sums
    prefix_sum = 0
    positive_count = 0
    
    # Step 3: Compute prefix sums and count positive ones
    for num in arr:
        prefix_sum += num
        if prefix_sum > 0:
            positive_count += 1
        else:
            break  # No need to continue as further sums will be non-positive
    
    return positive_count

# Example usage
arr = [-3,0,-2]
print(max_positive_prefix_sums(arr))  # Output should be 3

0


In [4]:
import pandas as pd
ambassdors=pd.Series([
    'France',
    'UK',
    'UK',
    'Italy',
    'Germany',
    'Germany',
    'Germany'
],index=[
    'Gerard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Witting',
    'Peter Ammon',
    'Klaus Scharioth'
])

In [5]:
ambassdors

Gerard Araud           France
Kim Darroch                UK
Peter Westmacott           UK
Armando Varricchio      Italy
Peter Witting         Germany
Peter Ammon           Germany
Klaus Scharioth       Germany
dtype: object

In [6]:
ambassdors.duplicated()

Gerard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Witting         False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [7]:
ambassdors.duplicated(keep='last')

Gerard Araud          False
Kim Darroch            True
Peter Westmacott      False
Armando Varricchio    False
Peter Witting          True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

In [8]:
import sqlite3

In [9]:
import numpy as np

In [10]:
list = [0,1,2,3,4,5,6,7,8]

In [11]:
array = np.array(list)

In [12]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
matrix = array.reshape((3,3))

In [14]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.mean(matrix,axis=0)

array([3., 4., 5.])

In [16]:
np.mean(matrix)

4.0

In [17]:
np.mean(matrix,axis=1)

array([1., 4., 7.])

In [20]:
def calculate(list):
    array=np.array(list)
    matrix=array.reshape((3,3))
    

    try:
        mean=[np.mean(matrix,axis=0).tolist(),np.mean(matrix,axis=1).tolist(),np.mean(array).tolist()]
        variance=[np.var(matrix,axis=0).tolist(),np.var(matrix,axis=1).tolist(),np.var(array).tolist()]
        standard_deviation = [(np.array(v) ** 0.5).tolist() for v in variance]

        max = [np.max(matrix, axis=0).tolist(), np.max(
            matrix, axis=1).tolist(), np.max(array).tolist()]
        min = [np.min(matrix, axis=0).tolist(), np.min(
            matrix, axis=1).tolist(), np.min(array).tolist()]
        sum = [np.sum(matrix, axis=0).tolist(), np.sum(
            matrix, axis=1).tolist(), np.sum(array).tolist()]
        
        calculations={
        'mean':mean,
        'variance':variance,
        'standard deviation':standard_deviation,
        'max':max,
        'min':min,
        'sum':sum
    }
    
    except ValueError:
        raise ValueError("List must contain nine numbers.")

    return calculations

In [24]:
list = [2,6,2,8,4,0,1,5,7]

In [25]:
calculate(list)

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}